import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ваши друзья - WishWave",
  description: "Generated by create next app",
};

export default function FriendsPage() {
  return <div>Friends</div>;
}
