"use client";
import Button from "@/components/ui/buttons/Button";
import { ThemeToggle } from "@/components/ui/buttons/ThemeToggle";
import ContentContainer from "@/components/ui/content_container/ContentContainer";
import Input from "@/components/ui/inputs/Input";
import Monogram from "@/components/ui/monogram/Monogram";
import Section from "@/components/ui/section/Section";
import type { Metadata } from "next";
import styles from "@/app/home.module.css";
import { useRouter } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Авторизация - WishWave",
//   description: "Generated by create next app",
// };

export default function LoginPage() {
  const router = useRouter();

  return (
    <>
      <ThemeToggle isAbsolute></ThemeToggle>
      <ContentContainer topBarSize="none" navigationType="none">
        <Section title="Авторизация" title_size="sm">
          <Input labelText="Почта" leadingIcon="mail" type="email" id="email" />
          <Input labelText="Пароль" leadingIcon="password" type="password" id="password" />
          <Button variant="text" isPadNone>
            Забыли пароль?
          </Button>
          <Button variant="filled" isFit={false}>
            Войти
          </Button>
        </Section>
        <Section align_items="center">
          <Section items_direction="row">
            Нет аккаунта?
            <Button variant="text" isPadNone onClick={() => router.push("/signup")}>
              Создайте его
            </Button>
          </Section>
        </Section>
      </ContentContainer>
      <Section align_items="center">
        <span className={styles.text_center + " " + styles.label}>
          Продолжая, вы соглашаетесь с{" "}
          <a
            className={styles.link}
            href="/documents#terms"
            target="_blank"
            rel="noopener noreferrer">
            Условиями обслуживания WishWave
          </a>{" "}
          и подтверждаете, что ознакомились с нашей{" "}
          <a
            className={styles.link}
            href="/documents#policy"
            target="_blank"
            rel="noopener noreferrer">
            Политикой конфиденциальности
          </a>
          .
        </span>
      </Section>
    </>
  );
}
