import NavigationBar from "@/components/ui/navigation_bar/NavigationBar";
import TopAppBar from "@/components/ui/top_app_bar/TopAppBar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Добавление желания - WishWave",
  description: "Generated by create next app",
};

export default function AddPage() {
  return <div>Добавить</div>;
}
