"use client";
import Button from "@/components/ui/buttons/Button";
import ContentContainer from "@/components/ui/content_container/ContentContainer";
import Monogram from "@/components/ui/monogram/Monogram";
import Section from "@/components/ui/section/Section";
import type { Metadata } from "next";
import styles from "@/app/home.module.css";
import { useRef } from "react";

// export const metadata: Metadata = {
//   title: "Главная - WishWave",
//   description: "Generated by create next app",
// };

export default function MainPage() {
  const scrollContainerRef = useRef<HTMLDivElement>(null);

  const handleWheel = (e: React.WheelEvent<HTMLDivElement>) => {
    if (scrollContainerRef.current) {
      // Предотвращаем вертикальный скролл страницы
      // e.preventDefault();
      // Скроллим контейнер по горизонтали
      scrollContainerRef.current.scrollLeft += e.deltaY;
    }
  };

  return (
    <>
      <Section title="Недавние обновления друзей" title_size="md">
        <div className={styles.row}>
          <div ref={scrollContainerRef} className={styles.scrollContainer} onWheel={handleWheel}>
            <Monogram letter="РК" size="md" color="primary" />
            <Monogram letter="РК" size="md" color="secondary" />
            <Monogram letter="РК" size="md" color="tertiary" />
            <Monogram letter="РК" size="md" color="primary" />
            <Monogram letter="РК" size="md" color="secondary" />
            <Monogram letter="РК" size="md" color="tertiary" />
            <Monogram letter="РК" size="md" color="primary" />
            <Monogram letter="РК" size="md" color="secondary" />
            <Monogram letter="РК" size="md" color="tertiary" />
            <Monogram letter="РК" size="md" color="primary" />
            <Monogram letter="РК" size="md" color="secondary" />
            <Monogram letter="РК" size="md" color="tertiary" />
            <Monogram letter="РК" size="md" color="primary" />
            <Monogram letter="РК" size="md" color="secondary" />
            <Monogram letter="РК" size="md" color="tertiary" />
            <Monogram letter="РК" size="md" color="primary" />
            <Monogram letter="РК" size="md" color="secondary" />
            <Monogram letter="РК" size="md" color="tertiary" />
          </div>
        </div>
      </Section>
      <Section title="Рекомендуем" title_size="md"></Section>
    </>
  );
}
