import Button from "@/components/ui/buttons/Button";
import ContentContainer from "@/components/ui/content_container/ContentContainer";
import Section from "@/components/ui/section/Section";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Главная - WishWave",
  description: "Generated by create next app",
};

export default function MainPage() {
  return (
    <Section title="Элементы главной страницы" title_size="md">
      <Button variant="filled">Кнопка</Button>
      <Button variant="elevated">Кнопка</Button>
      <Button variant="filled_tonal">Кнопка</Button>
      <Button variant="outlined">Кнопка</Button>
      <Button variant="text">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
      <Button variant="filled">Кнопка</Button>
    </Section>
  );
}
