import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ваш профиль - WishWave",
  description: "Generated by create next app",
};

export default function ProfilePage() {
  return <div>Profile</div>;
}
