import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "WishWave",
  description: "Generated by create next app",
};

export default function MainPage() {
  return <div>Main</div>;
}
