import Button from "@/components/ui/buttons/Button";
import List from "@/components/ui/list/List";
import ListItem from "@/components/ui/list/ListItem";
import Monogram from "@/components/ui/monogram/Monogram";
import Section from "@/components/ui/section/Section";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ваш профиль - WishWave",
  description: "Generated by create next app",
};

export default function ProfilePage() {
  return (
    <>
      <Section align_items="center">
        <Monogram letter="АС" size="lg"></Monogram>
        <div className="button_group flex gap-2">
          <Button variant="filled_tonal" icon="edit"></Button>
          <Button variant="filled_tonal" icon="delete"></Button>
        </div>
      </Section>
      <Section title="Публичная информация:" title_size="sm">
        <List>
          <ListItem
            condition={2}
            overline="Фамилия Имя"
            headline="Алекандр Сакунов"
            leading_type="icon"
            leading="person"
            trailing_type="icon"
          />
          <ListItem
            condition={2}
            overline="Дата рождения"
            headline="21.10.2003"
            leading_type="icon"
            leading="today"
            trailing_type="icon"
          />
          <ListItem
            condition={2}
            headline="Мужской"
            overline="Пол"
            leading_type="icon"
            leading="male"
            trailing_type="icon"
          />
        </List>
      </Section>

      <Section title="Приватная информация:" title_size="md">
        <List>
          <ListItem
            condition={2}
            overline="Почта"
            headline="sakunovss2003@mail.ru"
            leading_type="icon"
            leading="mail"
            trailing_type="icon"
          />
          <ListItem
            condition={2}
            overline="Телефон"
            headline="+7 (961) 999-97-57"
            leading_type="icon"
            leading="call"
            trailing_type="icon"
          />
        </List>
      </Section>

      <Section title="Социальные сети:" title_size="lg">
        <List>
          <ListItem
            condition={2}
            overline="Telegram"
            headline="sakunovss2003@mail.ru"
            leading_type="monogram"
            leading="TG"
            trailing_type="icon"
          />
          <ListItem
            condition={2}
            headline="ВКонтакте"
            leading_type="monogram"
            leading="ВК"
            trailing_type="icon"
          />
        </List>
      </Section>
    </>
  );
}
