"use client";
import Modal from "@/components/shared/modal/modal";
import Button from "@/components/ui/buttons/Button";
import List from "@/components/ui/list/List";
import ListItem from "@/components/ui/list/ListItem";
import Monogram from "@/components/ui/monogram/Monogram";
import Section from "@/components/ui/section/Section";
import type { Metadata } from "next";
import { useEffect, useState } from "react";
import style from "@/app/home.module.css";
import Footer from "@/components/shared/footer/footer";
import { useRouter } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Ваш профиль - WishWave",
//   description: "Generated by create next app",
// };

export default function ProfilePage() {
  //Роутер
  const router = useRouter();

  // Переменные
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {}, []);

  return (
    <>
      <Section align_items="center" padding_top_size="lg">
        <Monogram letter="" icon="person" size="md" isLoading={isLoading}></Monogram>
      </Section>
      <Section align_items="center">
        <span className={style.title}>{"..."}</span>
        <span className={style.body}>{"..."}</span>
      </Section>
      <Section
        title="Информация вашего профиля в сервсие WishWave"
        title_size="md"
        padding_top_size="lg"
        padding_bot_size="lg">
        <span className={style.body}>
          Здесь можно посмотреть или изменить личную информацию. Некоторые данные, например
          контактные, можно сделать доступными всем, чтобы с вами было проще связаться.
        </span>
      </Section>
      <Section>
        <hr />
      </Section>
      <Section title="Основная информация" title_size="sm" padding_top_size="lg">
        <span className={style.label}>
          Некоторая информация может быть видна другим пользователям сервиса WishWave. Узнать больше
        </span>
        <List withoutPad>
          <ListItem
            condition={2}
            overline="Фото профиля"
            leading_type="monogram"
            leading="АС"
            headline="Персонализирует ваш аккаунт"
            trailing_type="icon"
            isLoading={isLoading}
            onClick={() => {
              router.push("/profile/image");
            }}
          />

          <ListItem
            condition={2}
            overline="Имя"
            headline={"Не указано"}
            trailing_type="icon"
            isLoading={isLoading}
            onClick={() => {
              router.push("/profile/name");
            }}
          />
          <ListItem
            condition={2}
            overline="Дата рождения"
            headline="21 Октября, 2003"
            trailing_type="icon"
            isLoading={isLoading}
            onClick={() => {
              router.push("/profile/birthday");
            }}
          />
          <ListItem
            condition={2}
            headline="Мужской"
            overline="Пол"
            trailing_type="icon"
            isLoading={isLoading}
            onClick={() => {
              router.push("/profile/gender");
            }}
          />
          <ListItem
            condition={2}
            overline="Логин"
            headline={"Не указано"}
            trailing_type="icon"
            isLoading={isLoading}
            onClick={() => {
              router.push("/profile/login");
            }}
          />
          <ListItem
            condition={2}
            overline="Пароль"
            headline={"Нажмите, чтобы изменить"}
            trailing_type="icon"
            isLoading={isLoading}
            onClick={() => {
              router.push("/profile/password");
            }}
          />
        </List>
      </Section>
      <Section>
        <hr />
      </Section>
      <Section title="Контактная информация" title_size="sm" padding_top_size="lg">
        <List withoutPad>
          <ListItem
            condition={2}
            overline="Почта"
            headline={"Не указано"}
            trailing_type="icon"
            isLoading={isLoading}
            onClick={() => {
              router.push("/profile/email");
            }}
          />
          {/* <ListItem
            condition={2}
            overline="Телефон"
            headline="+7 (961) 999-97-57"
            trailing_type="icon"
            isLoading={isLoading}
            onClick={() => {
              alert("Смена телефона");
            }}
          /> */}
        </List>
      </Section>
      {/* <Section>
        <hr />
      </Section> */}

      {/* <Section title="Социальные сети:" title_size="sm" padding_top_size="lg">
        <List withoutPad>
          <ListItem
            condition={2}
            overline="Telegram"
            headline="@ssssov"
            trailing_type="icon"
            isLoading={isLoading}
            onClick={() => {
              alert("asas");
            }}
          />
          <ListItem
            condition={2}
            overline="ВКонтакте"
            headline="Отсутствует"
            trailing_type="icon"
            isLoading={isLoading}
            onClick={() => {
              alert("asas");
            }}
          />
        </List>
      </Section> */}
    </>
  );
}
