import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Авторизация - WishWave",
  description: "Generated by create next app",
};

export default function LoginPage() {
  return <div>Login</div>;
}
