import Input from "@/components/ui/inputs/Input";
import List from "@/components/ui/list/List";
import ListItem from "@/components/ui/list/ListItem";
import NavigationBar from "@/components/ui/navigation_bar/NavigationBar";
import Section from "@/components/ui/section/Section";
import TopAppBar from "@/components/ui/top_app_bar/TopAppBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ваши желания - WishWave",
  description: "Generated by create next app",
};

export default function MyPage() {
  return (
    <>
      <Section padding_top_size="lg">
        <Input labelText="Название" leadingIcon="search" trailingIcon="cancel"></Input>
      </Section>

      <Section title="Все ваши списки" padding_top_size="lg">
        <List withoutPad>
          <ListItem
            condition={2}
            headline="День рождения!"
            overline="21.10"
            leading_type="icon"
            leading="visibility"
            trailing_type="icon"
          />
          <ListItem
            condition={2}
            headline="Новый год"
            overline="01.01"
            leading_type="icon"
            leading="visibility"
            trailing_type="icon"
          />
          <ListItem
            condition={2}
            headline="Маме"
            overline="21.10"
            leading_type="icon"
            leading="visibility_off"
            trailing_type="icon"
          />
          <ListItem
            condition={2}
            headline="Новруз"
            overline="01.01"
            leading_type="icon"
            leading="visibility_off"
            trailing_type="icon"
          />
        </List>
      </Section>
    </>
  );
}
